name: 'dev'

# on a pull request and a push to the main branch
on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build-project:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: build project
        run: |
          cargo build --release
          cp target/release/field-day-map ../field-day-map
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: field-day-map-dev-${{ matrix.platform }}
          path: field-day-map
